"""Build the vendored Lucide icon set from the published npm tarball.

Lucide is ISC-licensed and ships one SVG per icon. The app needs two halves of the
same fact -- the drawing (for the browser) and the list of names (for the server,
which refuses to store an icon it could not draw) -- and two hand-kept copies of
735 names would drift within a week. So both are generated here, from one download,
and a test asserts they still agree.

    uv run tools/build-lucide.py 1.48.0

Nothing in the running app uses this: it is a build step, run by hand when the icon
set is worth updating, and it is the reason `static/vendor/lucide.js` and
`app/icons.py` are allowed to be boring.
"""

from __future__ import annotations

import io
import json
import re
import sys
import tarfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARBALL = "https://registry.npmjs.org/lucide-static/-/lucide-static-{version}.tgz"

#: Lucide draws on a 24x24 grid with a 2px stroke in `currentColor`, and every icon
#: is stroke-only (no fills). These are set once on the <svg> at render time rather
#: than repeated in each icon, which is most of why the vendored file stays small.
SVG_RE = re.compile(r"<svg[^>]*>(.*)</svg>", re.S)
INNER_WS = re.compile(r">\s+<")



def fetch(version: str) -> dict[str, str]:
    """Download one tarball and return {name: inner svg markup}."""
    url = TARBALL.format(version=version)
    print(f"fetching {url}")
    with urllib.request.urlopen(url, timeout=60) as resp:      # noqa: S310 -- a fixed URL
        blob = resp.read()
    icons: dict[str, str] = {}
    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as tar:
        for member in tar.getmembers():
            if not member.name.startswith("package/icons/") or not member.name.endswith(".svg"):
                continue
            name = Path(member.name).stem
            text = tar.extractfile(member).read().decode("utf-8")
            match = SVG_RE.search(text)
            if not match:
                print(f"  ! {name}: no <svg> content, skipped")
                continue
            inner = match.group(1).strip()
            # One line per icon, and no whitespace between tags: the file is read by
            # browsers, not by people, and every byte here is served on every load.
            inner = INNER_WS.sub("><", re.sub(r"\s*\n\s*", "", inner))
            # The `/>` stays. Stripping it to `>` looks like a free byte per tag and
            # turns `<path/><path/>` into `<path><path>` -- nested open elements, of
            # which a browser paints only the outermost. That is one broken icon for
            # every icon Lucide draws with more than one shape, which is most of them:
            # `brain` became a bare vertical line and `book-open` the same, and it read
            # as a rendering bug in the view rather than in this generator.
            icons[name] = inner
    return icons


def write_js(icons: dict[str, str], version: str, path: Path) -> None:
    header = (
        f"// Lucide {version} -- {len(icons)} icons, generated by tools/build-lucide.py.\n"
        "//\n"
        "// ISC License. Copyright (c) for portions of Lucide are held by Cole Bemis\n"
        "// 2013-2022, with other copyrights held by Lucide Contributors 2022.\n"
        "// Full license: https://github.com/lucide-icons/lucide/blob/main/LICENSE\n"
        "//\n"
        "// Do not edit: run `uv run tools/build-lucide.py " + version + "` instead.\n"
        "// Each value is the *inside* of the icon's <svg>: the drawing only. The\n"
        "// wrapper (viewBox, fill=none, stroke=currentColor, stroke-width) is applied\n"
        "// once by `iconSvg()` in static/js/icons.js, so an icon inherits text colour\n"
        "// and size like any other element.\n"
        f"export const LUCIDE_VERSION = {json.dumps(version)};\n\n"
        "export const ICONS = {\n"
    )
    lines = [f"\t{json.dumps(name)}: {json.dumps(markup)}," for name, markup in sorted(icons.items())]
    path.write_text(header + "\n".join(lines) + "\n};\n", encoding="utf-8")


def write_py(names: list[str], version: str, path: Path) -> None:
    body = (
        '"""The Lucide icon names this app knows, generated by tools/build-lucide.py.\n\n'
        f"Lucide {version}, {len(names)} icons. The drawings themselves live in\n"
        "`static/vendor/lucide.js`; this is the server's half of the same fact, so the API\n"
        "can *say* that a note's icon is not one it could draw -- a note is the person's\n"
        "own file, so an unknown name is kept and reported rather than refused, exactly\n"
        "like an address a browser cannot open. It is generated rather than typed because\n"
        "a hand-kept list of icon names is a list that is wrong by the next release.\n\n"
        'Do not edit: run `uv run tools/build-lucide.py ' + version + "` instead.\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        f"LUCIDE_VERSION = {version!r}\n\n"
        f"def _names() -> tuple[str, ...]:\n"
    )
    # Kept as one tuple literal per screenful so the diff of an update stays readable.
    chunks = [names[i:i + 6] for i in range(0, len(names), 6)]
    out = ['    """Every icon name, in Lucide\'s own order."""', "    return ("]
    for chunk in chunks:
        out.append("        " + " ".join(f"{n!r}," for n in chunk))
    out.append("    )")
    body += "\n".join(out) + "\n\n\nNAMES = _names()\n\n#: For the membership test the API runs on every save: a set, not a scan.\nNAME_SET = frozenset(NAMES)\n"
    path.write_text(body, encoding="utf-8")


def main() -> int:
    version = sys.argv[1] if len(sys.argv) > 1 else "1.48.0"
    icons = fetch(version)
    if not icons:
        print("no icons found -- refusing to write an empty set")
        return 1
    js_path = ROOT / "static" / "vendor" / "lucide.js"
    py_path = ROOT / "app" / "icons.py"
    write_js(icons, version, js_path)
    write_py(sorted(icons), version, py_path)
    print(f"wrote {js_path.relative_to(ROOT)} ({js_path.stat().st_size / 1024:.0f} KB, {len(icons)} icons)")
    print(f"wrote {py_path.relative_to(ROOT)} ({py_path.stat().st_size / 1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
